CREATE USER DB_REPL_USER REPLICATION LOGIN ENCRYPTED PASSWORD 'DB_REPL_PASSWORD';

CREATE DATABASE DB_DATABASE;

\c DB_DATABASE;

CREATE TABLE IF NOT EXISTS Emails (
    id SERIAL PRIMARY KEY,
    "Электронная почта" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Phone (
    id SERIAL PRIMARY KEY,
    "Номер телефона" VARCHAR(100)
);


INSERT INTO Emails ("Электронная почта") VALUES ('hruk@mail.ru'), ('kar@mail.ru');
INSERT INTO Phone ("Номер телефона") VALUES ('+79995552233'), ('89031029977');
GRANT SELECT ON ALL TABLES IN SCHEMA public TO DB_REPL_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT ON TABLES TO DB_REPL_USER;